export const SURAHS = [
  { n:1,  name:"Al-Fatihah",   ar:"الفاتحة",    a:7   },
  { n:2,  name:"Al-Baqarah",   ar:"البقرة",      a:286 },
  { n:3,  name:"Al-Imran",     ar:"آل عمران",    a:200 },
  { n:4,  name:"An-Nisa",      ar:"النساء",      a:176 },
  { n:5,  name:"Al-Maidah",    ar:"المائدة",     a:120 },
  { n:6,  name:"Al-Anam",      ar:"الأنعام",     a:165 },
  { n:7,  name:"Al-Araf",      ar:"الأعراف",     a:206 },
  { n:8,  name:"Al-Anfal",     ar:"الأنفال",     a:75  },
  { n:9,  name:"At-Tawbah",    ar:"التوبة",      a:129 },
  { n:10, name:"Yunus",        ar:"يونس",        a:109 },
  { n:11, name:"Hud",          ar:"هود",         a:123 },
  { n:12, name:"Yusuf",        ar:"يوسف",        a:111 },
  { n:13, name:"Ar-Rad",       ar:"الرعد",       a:43  },
  { n:14, name:"Ibrahim",      ar:"إبراهيم",     a:52  },
  { n:15, name:"Al-Hijr",      ar:"الحجر",       a:99  },
  { n:16, name:"An-Nahl",      ar:"النحل",       a:128 },
  { n:17, name:"Al-Isra",      ar:"الإسراء",     a:111 },
  { n:18, name:"Al-Kahf",      ar:"الكهف",       a:110 },
  { n:19, name:"Maryam",       ar:"مريم",        a:98  },
  { n:20, name:"Ta-Ha",        ar:"طه",          a:135 },
  { n:21, name:"Al-Anbiya",    ar:"الأنبياء",    a:112 },
  { n:22, name:"Al-Hajj",      ar:"الحج",        a:78  },
  { n:23, name:"Al-Muminun",   ar:"المؤمنون",    a:118 },
  { n:24, name:"An-Nur",       ar:"النور",       a:64  },
  { n:25, name:"Al-Furqan",    ar:"الفرقان",     a:77  },
  { n:26, name:"Ash-Shuara",   ar:"الشعراء",     a:227 },
  { n:27, name:"An-Naml",      ar:"النمل",       a:93  },
  { n:28, name:"Al-Qasas",     ar:"القصص",       a:88  },
  { n:29, name:"Al-Ankabut",   ar:"العنكبوت",    a:69  },
  { n:30, name:"Ar-Rum",       ar:"الروم",       a:60  },
  { n:31, name:"Luqman",       ar:"لقمان",       a:34  },
  { n:32, name:"As-Sajdah",    ar:"السجدة",      a:30  },
  { n:33, name:"Al-Ahzab",     ar:"الأحزاب",     a:73  },
  { n:34, name:"Saba",         ar:"سبأ",         a:54  },
  { n:35, name:"Fatir",        ar:"فاطر",        a:45  },
  { n:36, name:"Ya-Sin",       ar:"يس",          a:83  },
  { n:37, name:"As-Saffat",    ar:"الصافات",     a:182 },
  { n:38, name:"Sad",          ar:"ص",           a:88  },
  { n:39, name:"Az-Zumar",     ar:"الزمر",       a:75  },
  { n:40, name:"Ghafir",       ar:"غافر",        a:85  },
  { n:41, name:"Fussilat",     ar:"فصلت",        a:54  },
  { n:42, name:"Ash-Shura",    ar:"الشورى",      a:53  },
  { n:43, name:"Az-Zukhruf",   ar:"الزخرف",      a:89  },
  { n:44, name:"Ad-Dukhan",    ar:"الدخان",      a:59  },
  { n:45, name:"Al-Jathiyah",  ar:"الجاثية",     a:37  },
  { n:46, name:"Al-Ahqaf",     ar:"الأحقاف",     a:35  },
  { n:47, name:"Muhammad",     ar:"محمد",        a:38  },
  { n:48, name:"Al-Fath",      ar:"الفتح",       a:29  },
  { n:49, name:"Al-Hujurat",   ar:"الحجرات",     a:18  },
  { n:50, name:"Qaf",          ar:"ق",           a:45  },
  { n:51, name:"Ad-Dhariyat",  ar:"الذاريات",    a:60  },
  { n:52, name:"At-Tur",       ar:"الطور",       a:49  },
  { n:53, name:"An-Najm",      ar:"النجم",       a:62  },
  { n:54, name:"Al-Qamar",     ar:"القمر",       a:55  },
  { n:55, name:"Ar-Rahman",    ar:"الرحمن",      a:78  },
  { n:56, name:"Al-Waqiah",    ar:"الواقعة",     a:96  },
  { n:57, name:"Al-Hadid",     ar:"الحديد",      a:29  },
  { n:58, name:"Al-Mujadilah", ar:"المجادلة",    a:22  },
  { n:59, name:"Al-Hashr",     ar:"الحشر",       a:24  },
  { n:60, name:"Al-Mumtahanah",ar:"الممتحنة",    a:13  },
  { n:61, name:"As-Saf",       ar:"الصف",        a:14  },
  { n:62, name:"Al-Jumuah",    ar:"الجمعة",      a:11  },
  { n:63, name:"Al-Munafiqun", ar:"المنافقون",   a:11  },
  { n:64, name:"At-Taghabun",  ar:"التغابن",     a:18  },
  { n:65, name:"At-Talaq",     ar:"الطلاق",      a:12  },
  { n:66, name:"At-Tahrim",    ar:"التحريم",     a:12  },
  { n:67, name:"Al-Mulk",      ar:"الملك",       a:30  },
  { n:68, name:"Al-Qalam",     ar:"القلم",       a:52  },
  { n:69, name:"Al-Haqqah",    ar:"الحاقة",      a:52  },
  { n:70, name:"Al-Maarij",    ar:"المعارج",     a:44  },
  { n:71, name:"Nuh",          ar:"نوح",         a:28  },
  { n:72, name:"Al-Jinn",      ar:"الجن",        a:28  },
  { n:73, name:"Al-Muzzammil", ar:"المزمل",      a:20  },
  { n:74, name:"Al-Muddaththir",ar:"المدثر",     a:56  },
  { n:75, name:"Al-Qiyamah",   ar:"القيامة",     a:40  },
  { n:76, name:"Al-Insan",     ar:"الإنسان",     a:31  },
  { n:77, name:"Al-Mursalat",  ar:"المرسلات",    a:50  },
  { n:78, name:"An-Naba",      ar:"النبأ",       a:40  },
  { n:79, name:"An-Naziat",    ar:"النازعات",    a:46  },
  { n:80, name:"Abasa",        ar:"عبس",         a:42  },
  { n:81, name:"At-Takwir",    ar:"التكوير",     a:29  },
  { n:82, name:"Al-Infitar",   ar:"الانفطار",    a:19  },
  { n:83, name:"Al-Mutaffifin",ar:"المطففين",    a:36  },
  { n:84, name:"Al-Inshiqaq",  ar:"الانشقاق",    a:25  },
  { n:85, name:"Al-Buruj",     ar:"البروج",      a:22  },
  { n:86, name:"At-Tariq",     ar:"الطارق",      a:17  },
  { n:87, name:"Al-Ala",       ar:"الأعلى",      a:19  },
  { n:88, name:"Al-Ghashiyah", ar:"الغاشية",     a:26  },
  { n:89, name:"Al-Fajr",      ar:"الفجر",       a:30  },
  { n:90, name:"Al-Balad",     ar:"البلد",       a:20  },
  { n:91, name:"Ash-Shams",    ar:"الشمس",       a:15  },
  { n:92, name:"Al-Layl",      ar:"الليل",       a:21  },
  { n:93, name:"Ad-Duha",      ar:"الضحى",       a:11  },
  { n:94, name:"Ash-Sharh",    ar:"الشرح",       a:8   },
  { n:95, name:"At-Tin",       ar:"التين",       a:8   },
  { n:96, name:"Al-Alaq",      ar:"العلق",       a:19  },
  { n:97, name:"Al-Qadr",      ar:"القدر",       a:5   },
  { n:98, name:"Al-Bayyinah",  ar:"البينة",      a:8   },
  { n:99, name:"Az-Zalzalah",  ar:"الزلزلة",     a:8   },
  { n:100,name:"Al-Adiyat",    ar:"العاديات",    a:11  },
  { n:101,name:"Al-Qariah",    ar:"القارعة",     a:11  },
  { n:102,name:"At-Takathur",  ar:"التكاثر",     a:8   },
  { n:103,name:"Al-Asr",       ar:"العصر",       a:3   },
  { n:104,name:"Al-Humazah",   ar:"الهمزة",      a:9   },
  { n:105,name:"Al-Fil",       ar:"الفيل",       a:5   },
  { n:106,name:"Quraysh",      ar:"قريش",        a:4   },
  { n:107,name:"Al-Maun",      ar:"الماعون",     a:7   },
  { n:108,name:"Al-Kawthar",   ar:"الكوثر",      a:3   },
  { n:109,name:"Al-Kafirun",   ar:"الكافرون",    a:6   },
  { n:110,name:"An-Nasr",      ar:"النصر",       a:3   },
  { n:111,name:"Al-Masad",     ar:"المسد",       a:5   },
  { n:112,name:"Al-Ikhlas",    ar:"الإخلاص",     a:4   },
  { n:113,name:"Al-Falaq",     ar:"الفلق",       a:5   },
  { n:114,name:"An-Nas",       ar:"الناس",       a:6   },
];

export const TOTAL_AYAHS = SURAHS.reduce((s, r) => s + r.a, 0); // 6236
